baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Biz Analyst Docs"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "blue"
